on:
  release:
    types: [created]
  push:
    tags:
    - '*'

name: Build Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build release artifacts
        run: |
          shards install
          crystal spec -v --error-trace
          shards build --release
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/hace
